# @COPYRIGHT@
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE

Import('env')

from SCons.Util import CLVar

libs =  CLVar('clxx_info boost_serialization')

# rlib - "real" library
lib = env.SharedLibrary('../../clxx_s11n', 
    [ 'platform_info.cpp'
    , 'platform_query.cpp'
    , 'device_info.cpp'
    , 'device_query.cpp'
    , 'platform_layer_info.cpp'
    ],
    LIBS = libs
)

ilib = env.Install('${libdir}', lib)
env.Ignore("${INSTALL_SANDBOX}${libdir}", ilib)

ihdr = env.Install("${includedir}/clxx/s11n", env.Glob("*.hpp"))
env.Ignore("${INSTALL_SANDBOX}${includedir}/clxx/s11n", ihdr)

env.Alias('install-libclxx_s11n-headers', ihdr)
env.Alias('install-libclxx_s11n-lib', ilib)
env.Alias('install-libclxx_s11n-dev', ['install-libclxx_s11n-headers', 'install-libclxx_s11n-lib' ])
env.Alias('install','install-libclxx_s11n-dev')

# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=scons expandtab tabstop=4 shiftwidth=4:
