# @COPYRIGHT@
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE

Import(['env'])

from SCons.Util import CLVar

env.CxxTest('../check-libclxx_app', env.Glob('app/*.t.h') + env.Glob('app/*/*.t.h'),
           LIBS = CLVar('clxx_app boost_program_options'),
           CXXTEST_CPPPATH = ['..'],
           CXXTEST_LIBPATH = env.get('LIBPATH', CLVar()),
           CXXTEST_TARGET = 'check-libclxx_app')

env.CxxTest('../check-libclxx', env.Glob('*.t.h'),
           LIBS = CLVar('clxx_test OpenCL clxx_info'),
           CXXTEST_CPPPATH = ['..'],
           CXXTEST_LIBPATH = env.get('LIBPATH', CLVar()),
           CXXTEST_TARGET = 'check-libclxx')

env.CxxTest('../check-libclxx_util', env.Glob('util/*.t.h'),
           LIBS = CLVar(),
           CXXTEST_CPPPATH = ['..'],
           CXXTEST_LIBPATH = env.get('LIBPATH', CLVar()),
           CXXTEST_TARGET = 'check-libclxx_util')

env.CxxTest('../check-libclxx_info', env.Glob('info/*.t.h'),
           LIBS = CLVar('clxx_info'),
           CXXTEST_CPPPATH = ['..'],
           CXXTEST_LIBPATH = env.get('LIBPATH', CLVar()),
           CXXTEST_TARGET = 'check-libclxx_info')

env.CxxTest('../check-libclxx_s11n', env.Glob('s11n/*.t.h'),
           LIBS = CLVar('clxx_s11n clxx_info boost_serialization'),
           CXXTEST_CPPPATH = ['..'],
           CXXTEST_LIBPATH = env.get('LIBPATH', CLVar()),
           CXXTEST_TARGET = 'check-libclxx_s11n')

env.Alias('check', [ 'check-libclxx_app', 'check-libclxx',
                     'check-libclxx_util', 'check-libclxx_info',
                     'check-libclxx_s11n' ])

env.AlwaysBuild('check-libclxx_app')
env.AlwaysBuild('check-libclxx')
env.AlwaysBuild('check-libclxx_util')
env.AlwaysBuild('check-libclxx_info')
env.AlwaysBuild('check-libclxx_s11n')

# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=scons expandtab tabstop=4 shiftwidth=4:
