# @COPYRIGHT@
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE

Import('env')

from SCons.Util import CLVar

libs = CLVar('clxx_app clxx_io clxx clxx_s11n clxx_info')

lib = env.SharedLibrary('../../../clxx_app_clinfo',
    [ 'options_description.cpp'
    , 'common_options_description.cpp'
    , 'platform_general_options_description.cpp'
    , 'platform_detail_options_description.cpp'
    , 'device_general_options_description.cpp'
    , 'device_detail_options_description.cpp'
    , 'io_options_description.cpp'
    , 'create_query.cpp'
    , 'main.cpp' ],
    LIBS = libs
)

ilib = env.Install('${libdir}', lib)
env.Ignore("${INSTALL_SANDBOX}${libdir}", ilib)

ihdr = env.Install("${includedir}/clxx/app_clinfo", env.Glob("*.hpp"))
env.Ignore("${INSTALL_SANDBOX}${includedir}/clxx/app_clinfo", ihdr)

env.Alias('install-libclxx_app_clinfo-headers', ihdr)
env.Alias('install-libclxx_app_clinfo-lib', ilib)
env.Alias('install-libclxx_app_clinfo-dev', ['install-libclxx_app_clinfo-headers', 'install-libclxx_app_clinfo-lib' ])
env.Alias('install','install-libclxx_app_clinfo-dev')

# Local Variables:
# # tab-width:4
# # indent-tabs-mode:nil
# # End:
# vim: set syntax=scons expandtab tabstop=4 shiftwidth=4:
